# https://vector.dev/docs/reference/configuration/
data_dir: '/var/lib/vector'

api:
  enabled: true
  address: 0.0.0.0:8686

# https://vector.dev/docs/reference/configuration/sources/docker_logs/
# Ingest data by tailing one or more files
sources:
  docker:
    type: 'docker_logs'

# Structure and parse via Vector's Remap Language
transforms:
  empty_message_filter:
    inputs:
      - docker
    type: 'filter'
    condition: '.message != ""'
  docker_remap:
    inputs:
      - empty_message_filter
    type: 'remap'
    source: |
      del(.stream)
      del(.source_type)
      .service = del(.label."com.docker.compose.service") # api / web / redis / ...
      .project = del(.label."com.docker.compose.project") # mainnet / testnet
      .container_number = del(.label."com.docker.compose.container-number")
      .platform = "Docker"
      del(.label)

  api_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "api"'

  api_remap:
    inputs:
      - api_filter
    type: 'remap'
    source: | # noop
      #

  api_light_remap:
    inputs:
      - api_remap
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # Web logs
  web_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "web"'

  web_remap:
    inputs:
      - web_filter
    type: 'remap'
    source:
      | # Replace prepending iso date (web is an nginx service in production)
      .message = replace!(.message, r'^[\d-]+T[\d:.]+Z\s+', "")
      .message = replace(.message, r'^[\d\/]+ [\d:.]+ ', "")

  web_light_remap:
    inputs:
      - web_remap
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # Grafana logs
  grafana_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "grafana"'

  grafana_remap:
    inputs:
      - grafana_filter
    type: 'remap'
    source: | # Replace prepending iso date, log level and service
      .message = replace!(.message, r't=[\d-]+T[\d:.]+Z level=\S+\s+', "")

  # CDN Logs (nginx)
  cdn_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "cdn"'

  cdn_remap:
    inputs:
      - cdn_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^[\d-]+T[\d:.]+Z\s+', "")
      .message = replace(.message, r'^[\d\/]+ [\d:.]+ ', "")

  # Traefik logs
  traefik_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "traefik"'

  traefik_remap:
    inputs:
      - traefik_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^time=".+Z" level=\S+\s+', "")

  # Quickwit logs
  quickwit_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "quickwit"'

  quickwit_remap:
    inputs:
      - quickwit_filter
    type: 'remap'
    source:
      | # Remove ANSI escape codes for color formatting & prepending iso date
      .message = replace!(.message, r'\x1b\[[0-9;]*m', "")
      .message = replace(.message, r'^[\d-]+T[\d:.]+Z\s+', "")

  # Prometheus logs
  prometheus_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "prometheus"'

  prometheus_remap:
    inputs:
      - prometheus_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^ts=[\d-]+T[\d:.]+Z\s+', "")

  # Redis logs
  redis_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "redis"'

  redis_remap:
    inputs:
      - redis_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^.*[*#]\s+', "")

  redis_light_remap:
    inputs:
      - redis_remap
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # Postgres logs
  postgres_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "postgres"'

  postgres_remap:
    inputs:
      - postgres_filter
    type: 'remap'
    source: | # Replace prepending iso date and log level
      .message = replace!(.message, r'^[\d-]{10} [\d:.]+ UTC\s+\[\d+\]\s+[A-Z]+:\s+', "")

  postgres_light_remap:
    inputs:
      - postgres_remap
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # Seed logs
  seed_filter:
    inputs:
      - docker_remap
    type: 'filter'
    condition: '.service == "seed"'

  seed_remap:
    inputs:
      - seed_filter
    type: 'remap'
    source: | # Replace prepending iso date
      .message = replace!(.message, r'^\s?[\d-]+T[\d:.]+Z\s+', "")

  seed_light_remap:
    inputs:
      - seed_remap
    type: 'remap'
    source: | # Keep only message and timestamp
      .old = del(.)
      .message = format_timestamp!(.old.timestamp, "%Y-%m-%dT%H:%M:%S%.3fZ") + " " + .old.message ?? ""
      del(.old)

  # Merge all remaps into one
  all_remap:
    inputs:
      - web_remap
      - cdn_remap
      - api_remap
      - redis_remap
      - postgres_remap
      - seed_remap
      - traefik_remap
      - grafana_remap
      - quickwit_remap
      - prometheus_remap
    type: 'remap'
    source: | # noop
      #

# Send structured data to a short-term storage
sinks:
  raw:
    inputs:
      - docker
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/raw.log'
    encoding:
      codec: json

  raw_s3:
    inputs:
      - docker
    type: 'aws_s3'
    endpoint: ${S3_LOG_ENDPOINT}
    bucket: ${S3_LOG_BUCKET}
    region: ${S3_LOG_REGION}
    key_prefix: vector/%Y-%m-%d/raw.
    compression: gzip
    content_encoding: gzip
    content_type: application/gzip
    filename_append_uuid: false
    filename_extension: log.json.gz
    filename_time_format: '%Y-%m-%dT%Hh%Mm%Ss%3f'
    encoding:
      codec: json
    auth:
      access_key_id: ${S3_LOG_ACCESS_KEY}
      secret_access_key: ${S3_LOG_SECRET_KEY}

  compose:
    inputs:
      - all_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/remap.log'
    encoding:
      codec: json

  # Send logs to S3
  remap_s3:
    inputs:
      - all_remap
    type: 'aws_s3'
    endpoint: ${S3_LOG_ENDPOINT}
    bucket: ${S3_LOG_BUCKET}
    region: ${S3_LOG_REGION}
    key_prefix: vector/%Y-%m-%d/remap.
    compression: gzip
    content_encoding: gzip
    content_type: application/gzip
    filename_append_uuid: false
    filename_extension: log.json.gz
    filename_time_format: '%Y-%m-%dT%Hh%Mm%Ss%3f'
    encoding:
      codec: json
    auth:
      access_key_id: ${S3_LOG_ACCESS_KEY}
      secret_access_key: ${S3_LOG_SECRET_KEY}

  # API output
  api:
    inputs:
      - api_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/api.log'
    encoding:
      codec: json

  api_light:
    inputs:
      - api_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/api.log'
    encoding:
      codec: text

  # Web output
  web:
    inputs:
      - web_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/web.log'
    encoding:
      codec: json

  web_light:
    inputs:
      - web_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/web.log'
    encoding:
      codec: text

  # Redis output
  redis:
    inputs:
      - redis_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/redis.log'
    encoding:
      codec: json

  redis_light:
    inputs:
      - redis_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/redis.log'
    encoding:
      codec: text

  # Postgres output
  postgres:
    inputs:
      - postgres_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/postgres.log'
    encoding:
      codec: json

  postgres_light:
    inputs:
      - postgres_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/postgres.log'
    encoding:
      codec: text

  # Seed output
  seed:
    inputs:
      - seed_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/full/seed.log'
    encoding:
      codec: json

  seed_light:
    inputs:
      - seed_light_remap
    type: 'file'
    path: '/var/log/vector/%Y-%m-%d/light/seed.log'
    encoding:
      codec: text

  # Send logs to Quickwit
  quickwit_http:
    type: http
    method: post
    encoding:
      codec: json
    framing:
      method: newline_delimited
    inputs:
      - all_remap
    uri: 'http://quickwit:7280/api/v1/logs/ingest'
